# Generated by Django 4.1.7 on 2023-03-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='resenha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
